# Generated by Django 3.1.1 on 2020-09-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('RSCI', '1'), ('RSCII', '2'), ('RSCIII', '3')], max_length=6)),
                ('numeracao', models.CharField(max_length=2)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=2)),
                ('valor_maximo', models.IntegerField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('instituto', models.ManyToManyField(related_name='Instituto', to='core.Instituto')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
                ('valor_maximo', models.IntegerField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.itemrsc')),
            ],
        ),
    ]
