# Generated by Django 3.1.1 on 2020-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrsc',
            name='peso',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
