# Generated by Django 3.1.1 on 2020-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200903_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituto',
            options={'verbose_name': 'Instituto', 'verbose_name_plural': 'Institutos'},
        ),
        migrations.AlterModelOptions(
            name='itemrsc',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='subitem',
            options={'verbose_name': 'Subitem', 'verbose_name_plural': 'Subitens'},
        ),
        migrations.AddField(
            model_name='subitem',
            name='numeracao',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
